### ISSUE TITLE
OSError: [Errno 22] Invalid argument: 'Thu Jan 18 02:28:02 2018.csv'

### ISSUE THREAD

**Issue by marchtom** [joeddav/devol#22]
Hey,
I tried to run a code similar to Your demo.ipynb. After running this:
```
num_generations = 2
population_size = 2
num_epochs = 1

devol = DEvol(genome_handler)
model = devol.run(dataset, num_generations, population_size, num_epochs)
model.summary()
```
Error occurred:
```

Genome encoding and accuracy data stored at Thu Jan 18 02:28:02 2018.csv 

---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-7-68908626ba10> in <module>()
      3 num_epochs = 1
      4 
----> 5 devol = DEvol(genome_handler)
      6 model = devol.run(dataset, num_generations, population_size, num_epochs)
      7 model.summary()

e:\python\src\devol\devol.py in __init__(self, genome_handler, data_path)
     33 
     34         print("Genome encoding and accuracy data stored at", self.datafile, "\n")
---> 35         with open(self.datafile, 'a') as csvfile:
     36             writer = csv.writer(csvfile, delimiter=',', quotechar='"', quoting=csv.QUOTE_MINIMAL)
     37             genome = genome_handler.genome_representation() + ["Val Loss", "Val Accuracy"]

OSError: [Errno 22] Invalid argument: 'Thu Jan 18 02:28:02 2018.csv'
```

I'm using Python 3.6
Windows 10.

**Comment by kamenomagic** [comment]
Make sure your "\\" characters are escaped; maybe the spaces or colons aren't appreciated. 

Actually yeah it's the colons:
https://stackoverflow.com/questions/43196750/python-oserror-errno-22-invalid-argument

I would remove the spaces too if it gives you problems. Just a python/windows thing.

If it works, close the issue! Thanks.

**Comment by marchtom** [comment]
":" in file name was the problem. Thanks and I'm closing the issue.

**Comment by cordeirojoao** [comment]
If you're using Windows go the Devol repository, to file devol/devol.py
and change the following line of code
`self.datafile = data_path or (datetime.now().ctime() + '.csv')`

to
`self.datafile = data_path or (datetime.now().ctime() + '.csv').replace(":", "_").replace(" ", "_")`

The problem is the current library is using : and spaces on files names, and Windows have issues on that

Meanwhile a simples solution
Change your code to
devol = DEvol(genome_handler, "Devol_file")
