### ISSUE TITLE
About the installation

### ISSUE THREAD

**Issue by moctarjallo** [joeddav/devol#27]
Hey,

I have tried the github way of installing repositories:
python setup.py install
it says installed but i cannot import : 
import devol
It says: 
ImportError: No module named 'devol'
when trying to execute the demo notebook

What could be going wrong?

**Comment by gavinfernandes2012** [comment]
I think I've fixed the issue, it was an error on our side with the code, I've forked the repo and I'm just running a 2 generation test, if all goes well I'll create a pull request and this will be fixed. The test run should finish in about 40 minutes.

**Comment by gavinfernandes2012** [comment]
Alright the issue seems to be fixed, and I've created a pull request and I'm waiting for it to be merged by @joeddav . Till then you can use my fork of this repo: https://github.com/gavinfernandes2012/devol . Do test it and tell me whether the fix works for you.

**Comment by jgoodman8** [comment]
I have the same issue. I am using Google Colaboratory and I got Import errors `No module named devol` using Python2  and `cannot import name 'DEvol'` using Python3.

**Comment by joeddav** [comment]
Are you sure you're using the correct installations of python/pip (if there are multiple on your machine)? Does `pip show devol` show anything?
