### ISSUE TITLE
Feature Request: Fine tune an already existing model

### ISSUE THREAD

**Issue by MorleyMinde** [joeddav/devol#32]
This is an awesome help. I would like to be able to fine tune an already existing model using this algorithm.

Would it be possible that I feed in an existing model and start creating next generation models from it?

Also is it possible to add LSTM into the mix?

**Comment by joeddav** [comment]
Model tuning would be problematic since it searches for optimal architectures and not weights.

As for LSTMs, PRs would definitely be welcome, but I'm not actively developing this project so it would need to come from one of you lovely people.
