### ISSUE TITLE
 running for sequential dense model breaks it

### ISSUE THREAD

**Issue by d8sconz** [joeddav/devol#6]
I have a simple toy rnn lstm in keras. To run it through devol I set the convolution variables (max_conv_layers, max_filters) to 0 because I am not doing any convolutions. This obviously (in hindsight) triggered a division by zero error (or similar). Point being, running this just for a sequential dense model seems to break it. Scanning through the genome_handler.py file I see that convolution layers are required - they're absence is certainly not tested for.

**Comment by d8sconz** [comment]
The error I'm getting (still) is:

`Traceback (most recent call last):
  File "gene.py", line 80, in <module>  activations=["relu", "sigmoid", "linear"])
File "C:\Users\...\genome_handler.py", line 42, in __init__
    [2**i for i in range(3, int(math.log(max_filters, 2)) + 1)],
ValueError: math domain error`

I've set the convolution variables *max_conv_layers* and *max_filters* to zero because there are none in my model. You've closed the issue so I'm wondering now if I've missed something obvious, or the program is only for testing cnn's.

**Comment by joeddav** [comment]
Hey sorry about that. I closed it because I added the functionality to not include convolutional layers but tested it with `max_conv_layers` not equal to zero still. I've just fixed that - try pulling again.

Sorry about all the holes - this project was not thoroughly tested and all the attention was unexpected.

**Comment by d8sconz** [comment]
There is a huge need to test models. I saw you on the github trending page
and figured you would be in for a lot of attention. Well done.
